language: php

php:
  - 5.6
  - 7.1

before_script:
  - composer self-update
  - composer install --no-interaction
  - php bin/console doctrine:database:create 
  - php bin/console doctrine:schema:create 
  - php bin/console doctrine:fixtures:load -n 

script:
  - phpunit
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: flase
