<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllWithCategoryAndUser ($query = null) {
        $qb = $this->createQueryBuilder("p");
        if ($query) {
            $qb = $query($qb);
        }
        $query = $qb->getQuery();
        $query->setFetchMode("AppBundle\Entity\Post", "category", \Doctrine\ORM\Mapping\ClassMetadata::FETCH_EAGER);
        return $query->getResult();
    }

}
